wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.26
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      4: 3.7.6
      5: 0.10.26
      8:
      - 3
      - 5
learning_rate:
  desc: null
  value: 0.01
